services:
  frontend:
    build:
      context: frontend
    container_name: front
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - transcendence
  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: backend
    container_name: back
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./backend:/transcendence
    networks:
      - transcendence
  db:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    build:
      context: database
    container_name: db
    env_file:
      - .env
    networks:
      - transcendence
volumes:
  backend:
  frontend:
networks:
  transcendence:
