services:
  backend:
    build:
      context: backend
    container_name: back
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/transcendence
  frontend:
    build:
      context: frontend
    container_name: front
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
volumes:
  backend:
  frontend:
