services:
  frontend:
    build:
      context: frontend
    container_name: front
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - transcendence
  backend:
    build:
      context: backend
    container_name: back
    env_file:
      - .env
    volumes:
      - ./backend:/usr/transcendence
    networks:
      - transcendence
volumes:
  frontend:
  backend:
networks:
  transcendence:
