import { fetchDisplayTerms, sendRequest } from "../login-page/login-fetch.js";

const locales = [
	{
		code: 'en',
		label: 'English',
		translations: {
			login_welcome: 'Welcome!',
			login_username: 'Username',
			login_password: 'Password',
			login_sign_in: 'Sign In',
			login_or: 'or',
			login_forgot_password: 'Forgot password?',
			login_no_account: `Don't have an account? `,
			login_sign_up: '&nbsp;Sign up',
			login_create_account: 'Create an account',
			login_repeat_password: 'Repeat the password',
			login_example_username: 'username-example123',
			login_example_email: 'example@email.com',
			login_create: 'Create account',
			login_return_to: 'or return to&nbsp;',
			login_accept_terms: 'By signing up, you agree to our Privacy and Terms Conditions.',
			terms_policy: 'Terms and Privacy Policy',
			language: 'English',
			login_recover_password: 'Recover your password',
			login_email: 'Introduce your email',
			login_submit: 'Submit',
			login_reset_password_message: `We'll send you an email to reset your password`,
			fill_all_fields: 'Fill in all the fields',
			username_too_short: 'Username too short',
			username_too_long: 'Username too long (max 16 characters)',
			username_allowed_chars: 'Username can only contain lowercase and digits',
			passwords_not_match: `Passwords don't match`,
			password_too_short: 'Password too short',
			password_musts: `Please use at least one uppercase, lowercase, number and '*.-_'`,
			incorrect_inputs: 'Username or Password may be incorrect',
			username_exists: 'Username already exists',
			email_exists: 'Email already in use',
			password_not_valid: 'Password is not valid',
			user_success: 'User create successfully',
			email_sent_successfully: 'Email sent succesfully! Go check it to reset your password',
			// Home Page
			home_header: 'Home Page',
			home_welcome: 'Welcome<span id="username" class="text-[var(--dark-pink)]"> Username</span>!',
			home_modify: 'Modify profile',
			home_profile: 'Profile settings',
			home_logout: 'Log out',
			home_games: 'Games',
			home_friends: 'Friends',
			home_messages: 'Messages',
			home_statistics: 'Statistics',
			home_moonbit: '✨ Welcome to Moonbit! ✨ ',
			home_first_p: 'Here, you can jump into classic games like <b class="text-white">Pong</b> or <b class="text-white">Connect Four</b>, play quick matches or join friendly <b class="text-white">tournaments</b>, with people nearby.',
			home_second_p: 'Feel like chatting? The <b class="text-white">chat</b> is always open: say hi, share a laugh, or plan your next game. You can also check out your <b class="text-white">Friends Page</b>, invite others to play, and see what they\'re up to.',
			home_third_p: 'And of course, this world is yours to make your own: visit your <b class="text-white">Profile</b> to personalize how you look and feel in this starry pixel space.',
			home_fourth_p: 'So go ahead: explore, play, and have fun. We’re happy you’re here. 🌟',
			stats_header: 'Statistics',
			stats_pong: 'Pong',
			stats_connect: 'Connect4',
			stats_historical: 'Historical',
			stats_dash: 'Dashboard',
			wins: 'Wins',
			losses: 'Losses',
			classic: 'Classic',
			chaos: 'Chaos',
			crazy_tokens: `CrazyTokens`,
			score_last_10: 'Score in the last 10 games',
			modify_header: 'Modify Profile',
			modify_upload_photo: 'Upload a photo',
			modify_create_avatar: 'Create an Avatar',
			modify_username: 'Username: ',
			modify_nick: 'Nick: ',
			modify_description: 'Description: ',
			modify_account: 'Account creation date: ',
			modify_wins: 'Total wins',
			modify_losses: 'Total losses',
			modify_avatar_creator: 'Avatar Creator',
			modify_save_changes: 'Save Changes',
			modify_empty_nickname: 'Nickname cannot be empty',
			modify_empty_description: 'Description cannot be empty',
			modify_select_options: 'Select 4 options',
			// Settings
			settings_title: 'Settings',
			settings_change_password: 'Change password',
			settings_two_factor: 'Configure 2 Factor-Authentication',
			settings_blocked_accounts: 'Blocked Accounts',
			settings_delete_account: 'Delete account',
			settings_current_password: 'Current Password',
			settings_new_password: 'New Password',
			settings_confirm_password: 'Confirm New Password',
			settings_submit_changes: 'Submit Changes',
			settings_auth: 'Two-Factor Auth',
			settings_auth_message: 'Introduce the 6-digits code associated to your account',
			settings_delete: 'Delete your account',
			settings_email: 'Introduce your email',
			settings_password: 'Introduce your password',
			settings_type_delete: `Type 'Delete'`,
			settings_fill_form: `Fill the form to delete your account`,
			settings_password_success: `Password changed successfully`,
			settings_wrong_delete: 'Incorrect confirm message',
			settings_delete_success: 'Account deleted successfully',
			settings_delete_message: `Your account has been deleted. <br/>If you log-in with your credentials in the next 30 days you'll recover it. <br/>We'll miss you!!`,
			settings_disable_2fa: `2FA disabled successfully`,
			settings_enable_2fa: `2FA enabled successfully`,
			settings_unblock_success: `User unblocked successfully`,
			settings_activate: 'Activate',
			settings_deactivate: 'Deactivate',
			// Friends
			friends_title: 'Friends',
			friends_list: 'Friends List',
			friends_invitations: 'Invitations',
			friends_search: 'Search a friend',
			friends_received: 'Received',
			friends_sent: 'Sent',
			friends_block_title: 'Block a friend',
			friends_cancel: 'Cancel',
			friends_block: 'Block',
			friends_block_m1: `Are you sure you want to <span class="text-[var(--alert)]">block</span> your friend?`,
			friends_block_m2: `Once done you can revert it in <span class="text-[var(--violet)]">settings</span>`,
			friends_online: 'Online',
			friends_offline: 'Offline',
			friends_delete: 'Delete',
			friends_pong_played: 'Pong Games Played: ',
			friends_pong_wins: 'Pong Wins Rate: ',
			friends_pong_losses: 'Pong Losses Rate: ',
			friends_connect_played: 'Connect Four Games Played: ',
			friends_connect_wins: 'Connect Four Wins Rate: ',
			friends_connect_losses: 'Connect Four Loses Rate: ',
			friends_user_not_found: 'User Not Found',
			// Messages
			messages_title: 'Chat Room',
			messages_friend_name: 'Friend name',
			messages_chat: 'Chat with your friends',
			messages_classic_pong: 'Classic Pong',
			messages_chaos_pong: 'Chaos Pong',
			messages_classic_connect: 'Classic Connect4',
			messages_crazy_connect: 'CrazyTokens Connect4',
			messages_not_friend: `You're not friends with this user`,
			// Select Game
			select_title: 'Game Selection',
			select_pong_description: 'Classic table tennis game. Challenge your friends in real-time!',
			select_pong_button: 'Play Pong',
			select_connect_title: 'Connect 4',
			select_connect_description: `Connect four pieces in a row to win. Strategic and fun!`,
			select_connect_button: 'Play Connect 4',
			select_tournament_title: 'Tournament',
			select_tournament_description: 'Create tournaments for both games!',
			select_tournament_button: 'Create Tournament',
			select_game_mode: 'Game Mode',
			select_normal_mode: 'Normal Mode',
			select_custom_mode: 'Custom Mode',
			select_remote: 'Remote Player',
			select_local: 'Local Game',
			select_play_ai: 'Play vs AI',
			select_custom_remote: 'Custom Remote',
			select_custom_local: 'Custom Local',
			select_custom_ai: 'Custom AI',
			select_create_tournament: 'Create Tournament',
			select_join_tournament: 'Join Tournament',
			select_search_error: '<p>Error searching players</p>',
			select_invalid_data: '<p>Error: Invalid data format</p>',
			select_no_found: '<p>No players found</p>',
			select_invite_custom: 'Invite to Custom Game',
			select_invite_normal: 'Invite to Game',
			select_invitation_sent: 'Invitation sent to',
			select_ready: 'Ready to Play',
			select_player_one: 'Player 1: <span class="host">Default</span>',
			select_player_two: 'Player 2: <span></span>',
			select_start: 'Start game',
			select_view_tournament: 'View Current Tournament',
			select_add_account: 'Add Account',
			select_participants: 'Participants',
			select_tournament_player_one: 'Player 1: <span class="player">Default</span>',
			select_tournament_player_two: 'Player 2: <span class="player">Default</span>',
			select_tournament_player_three: 'Player 3: <span class="player">Default</span>',
			select_tournament_player_four: 'Player 4: <span class="player">Default</span>',
			select_start_tournament: 'Start Tournament',
			select_tournament_name: 'Tournament name',

			// 404
			page_404: '404 Page Not Found',
			// Recover password
			reset_password: 'Introduce your new password',
			reset_password_again: 'Introduce your new password again',
			reset_message: `Remember your password must contain at least one uppercase, lowercase, number and '*.-_'`,
			reset_success: `Change of password was successful. You can now return to login page!`,
			// 2FA
			twofa_validate: 'Validate 2FA',
			invalid_code: 'Invalid code',
		}
	},
	{
		code: 'es',
		label: 'Español',
		translations: {
			login_welcome: 'Bienvenido',
			login_username: 'Nombre de usuario',
			login_password: 'Contraseña',
			login_sign_in: 'Iniciar Sesión',
			login_or: 'o',
			login_forgot_password: '¿Olvidaste tu contraseña?',
			login_no_account: `¿No tienes una cuenta? `,
			login_sign_up: '&nbsp;Regístrate',
			login_create_account: 'Registro',
			login_repeat_password: 'Repite la contraseña',
			login_example_username: 'usuario-ejemplo123',
			login_example_email: 'ejemplo@email.es',
			login_create: 'Create una cuenta',
			login_return_to: 'o vuelve a&nbsp;',
			login_accept_terms: 'Al registrarte, aceptas nuestros Términos y Condiciones de Privacidad',
			terms_policy: 'Términos y Políticas de Privacidad',
			language: 'Español',
			login_recover_password: 'Recupera tu contraseña',
			login_email: 'Introduce tu email',
			login_submit: 'Enviar',
			login_reset_password_message: `Te mandaremos un correo para que recuperes tu contraseña`,
			fill_all_fields: 'Rellena todos los campos',
			username_too_short: 'Nombre de usuario demasiado corto',
			username_too_long: 'Nombre de usuario demasiado largo (max 16 caracteres)',
			username_allowed_chars: 'El nombre de usuario sólo puede contener minúsculas y barra baja',
			passwords_not_match: `Las contraseñas no coinciden`,
			password_too_short: 'Contraseña demasiado corta',
			password_musts: `Por favor utiliza por lo menos una mayúscula, minúscula, número y '*.-_'`,
			incorrect_inputs: 'Nombre de usuario o contraseña incorrectos',
			username_exists: 'Nombre de usuario en uso',
			email_exists: 'Email en uso',
			password_not_valid: 'La contraseña no es válida',
			user_success: 'Usuario creado correctamente',
			email_sent_successfully: '¡Correo enviado con éxito! Revísalo para cambiar tu contraseña',
			// Home
			home_header: 'Página de Inicio',
			home_welcome: '¡Bienvenido<span id="username" class="text-[var(--dark-pink)]"> Username</span>!',
			home_modify: 'Modificar perfil',
			home_profile: 'Opciones del perfil',
			home_logout: 'Cerrar sesión',
			home_games: 'Juegos',
			home_friends: 'Amigos',
			home_messages: 'Mensajes',
			home_statistics: 'Estadísticas',
			home_moonbit: '✨ ¡Bienvenido a Moonbit! ✨ ',
			home_first_p: 'Aquí podrás disfrutar de juegos clásicos como <b class="text-white">Pong</b> o <b class="text-white">Cuatro en raya</b>, juega partidas rápidas o únete a <b class="text-white">torneos</b> amistosos.',
			home_second_p: '¿Quieres hablar un rato? El <b class="text-white">chat</b> siempre está abierto: di hola, comparte unas risas o prepara tu siguiente partida. También puedes echarle un vistazo a tu <b class="text-white">Página de Amigos</b>, invitar a otros a jugar y ver qué están haciendo.',
			home_third_p: 'Y por supuesto, este mundo te pertenece para hacerlo tuyo: visita tu <b class="text-white">Perfil</b> para personalizar cómo se te ve en este estrellado espacio pixelado.',
			home_fourth_p: 'Así que adelante: explora, juega, y diviértete. Estamos felices de que estés aquí. 🌟',
			stats_header: 'Estadísticas',
			stats_pong: 'Pong',
			stats_connect: 'Cuatro en raya',
			stats_historical: 'Historial',
			stats_dash: 'Panel',
			wins: 'Victorias',
			losses: 'Derrotas',
			classic: 'Clásico',
			chaos: 'Caos',
			crazy_tokens: 'Alocadas',
			score_last_10: 'Puntuación en las últimas 10 partidas',
			modify_header: 'Modificar Perfil',
			modify_upload_photo: 'Sube una foto',
			modify_create_avatar: 'Crea un avatar',
			modify_username: 'Nombre de usuario: ',
			modify_nick: 'Apodo: ',
			modify_description: 'Descripción: ',
			modify_account: 'Fecha de creación de cuenta: ',
			modify_wins: 'Victorias totales',
			modify_losses: 'Derrotas totales',
			modify_avatar_creator: 'Creador de Avatares',
			modify_save_changes: 'Guardar Cambios',
			modify_empty_nickname: 'El apodo no puede estar vacío',
			modify_empty_description: 'La descripción no puede estar vacía',
			modify_select_options: 'Selecciona 4 opciones',
			// Settings
			settings_title: 'Ajustes',
			settings_change_password: 'Cambiar contraseña',
			settings_two_factor: 'Configurar Autenticación de 2 Factores',
			settings_blocked_accounts: 'Cuentas bloqueadas',
			settings_delete_account: 'Eliminar cuenta',
			settings_current_password: 'Contraseña Actual',
			settings_new_password: 'Nueva Contraseña',
			settings_confirm_password: 'Confirma la Nueva Contraseña',
			settings_submit_changes: 'Enviar Cambios',
			settings_auth: '2FA',
			settings_auth_message: 'Introduce el código de 6 dígitos asociado a tu cuenta',
			settings_delete: 'Elimina tu cuenta',
			settings_email: 'Introduce tu correo',
			settings_password: 'Introduce tu contraseña',
			settings_type_delete: `Introduce 'Delete'`,
			settings_fill_form: `Rellena el formulario para eliminar tu cuenta`,
			settings_password_success: `Contraseña cambiada con éxito`,
			settings_wrong_delete: 'Mensaje de confirmación incorrecto',
			settings_delete_success: 'Cuenta eliminada con éxito',
			settings_delete_message: `Tu cuenta ha sido eliminada. <br/>Si inicias sesión en los próximos 30 días la recuperarás. <br/>¡Te echaremos de menos!`,
			settings_disable_2fa: `2FA desactivado con éxito`,
			settings_enable_2fa: `2FA habilitado con éxito`,
			settings_unblock_success: `Usuario desbloqueado con éxito`,
			settings_activate: 'Activar',
			settings_deactivate: 'Desactivar',
			// Friends
			friends_title: 'Amigos',
			friends_list: 'Lista de Amigos',
			friends_invitations: 'Invitaciones',
			friends_search: 'Buscar a un amigo',
			friends_received: 'Recibidas',
			friends_sent: 'Enviadas',
			friends_block_title: 'Bloquea a un amigo',
			friends_cancel: 'Cancelar',
			friends_block: 'Bloquear',
			friends_block_m1: `¿Estás seguro de que quieres <span class="text-[var(--alert)]">bloquear</span> a esta persona?`,
			friends_block_m2: `Una vez hecho, puedes revertirlo en <span class="text-[var(--violet)]">ajustes</span>`,
			friends_online: 'En línea',
			friends_offline: 'Desconectado',
			friends_delete: 'Eliminar',
			friends_pong_played: 'Partidas de Pong Jugadas: ',
			friends_pong_wins: 'Victorias de Pong: ',
			friends_pong_losses: 'Derrotas de Pong: ',
			friends_connect_played: 'Partidas de Cuatro en Raya Jugadas: ',
			friends_connect_wins: 'Victorias de Cuatro en Raya: ',
			friends_connect_losses: 'Derrotas de Cuatro en Raya: ',
			friends_user_not_found: 'Usuario no encontrado',
			// Messages
			messages_title: 'Sala de Chat',
			messages_friend_name: 'Nombre de amigo',
			messages_chat: 'Habla con tus amigos',
			messages_classic_pong: 'Pong Clásico',
			messages_chaos_pong: 'Pong Caos',
			messages_classic_connect: 'Cuatro en Raya Clásico',
			messages_crazy_connect: 'Cuatro en Raya Fichas Alocadas',
			messages_not_friend: `No eres amigo de este usuario`,
			// Select Game
			select_title: 'Selección de Juego',
			select_pong_description: 'El clásico juego de tenis de mesa. ¡Desafía a tus amigos en tiempo real!',
			select_pong_button: 'Jugar al Pong',
			select_connect_title: 'Cuatro en Raya',
			select_connect_description: `Conecta cuatro piezas seguidas para ganar. ¡Estratégico y divertido!`,
			select_connect_button: 'Jugar Cuatro en Raya',
			select_tournament_title: 'Torneo',
			select_tournament_description: '¡Crea torneos para ambos juegos!',
			select_tournament_button: 'Crear Torneo',
			select_game_mode: 'Modo de Juego',
			select_normal_mode: 'Modo Normal',
			select_custom_mode: 'Modo Personalizado',
			select_remote: 'Juego en Remoto',
			select_local: 'Juego en Local',
			select_play_ai: 'Juego contra la IA',
			select_custom_remote: 'Remoto Personalizado',
			select_custom_local: 'Local Personalizado',
			select_custom_ai: 'IA Personalizada',
			select_create_tournament: 'Crear un Torneo',
			select_join_tournament: 'Unirse a un Torneo',
			select_search_error: '<p>Error buscando jugadores</p>',
			select_invalid_data: '<p>Error: Formato de dato inválido</p>',
			select_no_found: '<p>Ningún jugador encontrado</p>',
			select_invite_custom: 'Invitar a juego personalizado',
			select_invite_normal: 'Invitar a jugar',
			select_invitation_sent: 'Invitación enviada a',
			select_ready: 'Listas para Jugar',
			select_player_one: 'Jugador 1: <span class="host">Por defecto</span>',
			select_player_two: 'Jugador 2: <span></span>',
			select_start: 'Iniciar partida',
			select_view_tournament: 'Ver torneo actual',
			select_add_account: 'Añadir cuenta',
			select_participants: 'Participantes',
			select_tournament_player_one: 'Jugador 1: <span class="player">Por defecto</span>',
			select_tournament_player_two: 'Jugador 2: <span class="player">Por defecto</span>',
			select_tournament_player_three: 'Jugador 3: <span class="player">Por defecto</span>',
			select_tournament_player_four: 'Jugador 4: <span class="player">Por defecto</span>',
			select_start_tournament: 'Comenzar Torneo',
			select_tournament_name: 'Nombre del torneo',
			// 404
			page_404: '404 Página No Encontrada',
			// Recover password
			reset_password: 'Introduce tu nueva contraseña',
			reset_password_again: 'Repite tu nueva contraseña',
			reset_message: `Recuerde que su contraseña debe contener al menos una mayúscula, una minúscula, un número y '*.-_'`,
			reset_success: `¡El cambio de contraseña se ha realizado correctamente! Puedes volver a la página de inicio de sesión.`,
			// 2FA
			twofa_validate: 'Valida 2FA',
			invalid_code: 'Código Inválido',
		}
	},
	{
		code: 'fr',
		label: 'Français',
		translations: {
			login_welcome: 'Bienvenue !',
			login_username: "Nom d'utilisateur",
			login_password: 'Mot de passe',
			login_sign_in: 'Se connecter',
			login_or: 'ou',
			login_forgot_password: 'Mot de passe oublié ?',
			login_no_account: `Vous n'avez pas de compte ? `,
			login_sign_up: '&nbsp;Inscrivez-vous',
			login_create_account: 'Créer un compte',
			login_repeat_password: 'Répétez le mot de passe',
			login_example_username: "nomutilisateur-exemple123",
			login_example_email: 'exemple@email.com',
			login_create: 'Créer un compte',
			login_return_to: 'ou retour à&nbsp;',
			login_accept_terms: "En vous inscrivant, vous acceptez notre politique de confidentialité et nos conditions d'utilisation.",
			terms_policy: 'Conditions et politique de confidentialité',
			language: 'Français',
			login_recover_password: 'Récupérer votre mot de passe',
			login_email: 'Entrez votre email',
			login_submit: 'Envoyer',
			login_reset_password_message: 'Nous vous enverrons un e-mail pour réinitialiser votre mot de passe',
			fill_all_fields: 'Remplissez tous les champs',
			username_too_short: "Nom d'utilisateur trop court",
			username_too_long: "Nom d'utilisateur trop long (16 caractères max)",
			username_allowed_chars: "Le nom d'utilisateur ne peut contenir que des lettres minuscules et des chiffres",
			passwords_not_match: 'Les mots de passe ne correspondent pas',
			password_too_short: 'Mot de passe trop court',
			password_musts: "Utilisez au moins une majuscule, une minuscule, un chiffre et un des caractères '*.-_'",
			incorrect_inputs: "Nom d'utilisateur ou mot de passe incorrect",
			username_exists: "Le nom d'utilisateur existe déjà",
			email_exists: 'Adresse e-mail déjà utilisée',
			password_not_valid: 'Mot de passe non valide',
			user_success: 'Utilisateur créé avec succès',
			email_sent_successfully: 'E-mail envoyé avec succès ! Vérifiez votre boîte de réception pour réinitialiser votre mot de passe',
			home_header: 'Page d’accueil',
			home_welcome: 'Bienvenue<span id="username" class="text-[var(--dark-pink)]"> NomUtilisateur</span> !',
			home_modify: 'Modifier le profil',
			home_profile: 'Paramètres du profil',
			home_logout: 'Se déconnecter',
			home_games: 'Jeux',
			home_friends: 'Amis',
			home_messages: 'Messages',
			home_statistics: 'Statistiques',
			home_moonbit: '✨ Bienvenue sur Moonbit ! ✨',
			home_first_p: 'Ici, vous pouvez jouer à des jeux classiques comme <b class="text-white">Pong</b> ou <b class="text-white">Puissance 4</b>, participer à des parties rapides ou à des <b class="text-white">tournois</b> avec des joueurs proches.',
			home_second_p: 'Envie de discuter ? Le <b class="text-white">chat</b> est toujours ouvert : dites bonjour, partagez un moment ou planifiez votre prochaine partie. Consultez votre <b class="text-white">page Amis</b> pour inviter d’autres joueurs et voir ce qu’ils font.',
			home_third_p: 'Et bien sûr, ce monde est le vôtre : visitez votre <b class="text-white">profil</b> pour personnaliser votre apparence dans cet univers pixelisé étoilé.',
			home_fourth_p: 'Alors allez-y : explorez, jouez, amusez-vous. Nous sommes heureux de vous avoir ici. 🌟',
			stats_header: 'Statistiques',
			stats_pong: 'Pong',
			stats_connect: 'Puissance 4',
			stats_historical: 'Historique',
			stats_dash: 'Panneau',
			wins: 'Victoires',
			losses: 'Défaites',
			classic: 'Classique',
			chaos: 'Chaos',
			crazy_tokens: 'JetonsFous',
			score_last_10: 'Score des 10 dernières parties',
			modify_header: 'Modifier le profil',
			modify_upload_photo: 'Télécharger une photo',
			modify_create_avatar: 'Créer un avatar',
			modify_username: "Nom d'utilisateur : ",
			modify_nick: 'Pseudo : ',
			modify_description: 'Description : ',
			modify_account: 'Date de création du compte : ',
			modify_wins: 'Victoires totales',
			modify_losses: 'Défaites totales',
			modify_avatar_creator: 'Créateur d’avatar',
			modify_save_changes: 'Enregistrer les modifications',
			modify_empty_nickname: 'Le pseudo ne peut pas être vide',
			modify_empty_description: 'La description ne peut pas être vide',
			modify_select_options: 'Sélectionnez 4 options',
			settings_title: 'Paramètres',
			settings_change_password: 'Changer le mot de passe',
			settings_two_factor: 'Configurer l’authentification à deux facteurs',
			settings_blocked_accounts: 'Comptes bloqués',
			settings_delete_account: 'Supprimer le compte',
			settings_current_password: 'Mot de passe actuel',
			settings_new_password: 'Nouveau mot de passe',
			settings_confirm_password: 'Confirmer le nouveau mot de passe',
			settings_submit_changes: 'Soumettre les modifications',
			settings_auth: '2FA',
			settings_auth_message: 'Entrez le code à 6 chiffres associé à votre compte',
			settings_delete: 'Supprimer votre compte',
			settings_email: 'Entrez votre adresse email',
			settings_password: 'Entrez votre mot de passe',
			settings_type_delete: `Tapez 'Supprimer'`,
			settings_fill_form: 'Remplissez le formulaire pour supprimer votre compte',
			settings_password_success: 'Mot de passe modifié avec succès',
			settings_wrong_delete: 'Message de confirmation incorrect',
			settings_delete_success: 'Compte supprimé avec succès',
			settings_delete_message: `Votre compte a été supprimé. <br/>Si vous vous reconnectez avec vos identifiants dans les 30 jours, vous le récupérerez. <br/>Vous allez nous manquer !!`,
			settings_disable_2fa: '2FA désactivé avec succès',
			settings_enable_2fa: '2FA activé avec succès',
			settings_unblock_success: 'Utilisateur débloqué avec succès',
			settings_activate: 'Activer',
			settings_deactivate: 'Désactiver',
			friends_title: 'Amis',
			friends_list: 'Liste d’amis',
			friends_invitations: 'Invitations',
			friends_search: 'Rechercher un ami',
			friends_received: 'Reçues',
			friends_sent: 'Envoyées',
			friends_block_title: 'Bloquer un ami',
			friends_cancel: 'Annuler',
			friends_block: 'Bloquer',
			friends_block_m1: `Êtes-vous sûr de vouloir <span class="text-[var(--alert)]">bloquer</span> cet ami ?`,
			friends_block_m2: `Vous pourrez annuler cela dans les <span class="text-[var(--violet)]">paramètres</span>`,
			friends_online: 'En ligne',
			friends_offline: 'Hors ligne',
			friends_delete: 'Supprimer',
			friends_pong_played: 'Parties de Pong jouées : ',
			friends_pong_wins: 'Taux de victoires à Pong : ',
			friends_pong_losses: 'Taux de défaites à Pong : ',
			friends_connect_played: 'Parties de Puissance 4 jouées : ',
			friends_connect_wins: 'Taux de victoires à Puissance 4 : ',
			friends_connect_losses: 'Taux de défaites à Puissance 4 : ',
			friends_user_not_found: 'Utilisateur introuvable',
			messages_title: 'Salle de Chat',
			messages_friend_name: 'Nom de l’ami',
			messages_chat: 'Discutez avec vos amis',
			messages_classic_pong: 'Pong Classique',
			messages_chaos_pong: 'Pong Chaos',
			messages_classic_connect: 'Puissance 4 Classique',
			messages_crazy_connect: 'Puissance 4 JetonsFous',
			messages_not_friend: "Vous n'êtes pas ami avec cet utilisateur",
			select_title: 'Sélection des jeux',
			select_pong_description: 'Jeu de tennis de table classique. Défiez vos amis en temps réel !',
			select_pong_button: 'Jouer à Pong',
			select_connect_title: 'Puissance 4',
			select_connect_description: 'Alignez quatre pièces pour gagner. Stratégique et amusant !',
			select_connect_button: 'Jouer à Puissance 4',
			select_tournament_title: 'Tournoi',
			select_tournament_description: 'Créez des tournois pour les deux jeux !',
			select_tournament_button: 'Créer un tournoi',
			select_game_mode: 'Mode de jeu',
			select_normal_mode: 'Mode normal',
			select_custom_mode: 'Mode personnalisé',
			select_remote: 'Joueur distant',
			select_local: 'Jeu local',
			select_play_ai: 'Jouer contre IA',
			select_custom_remote: 'Distant personnalisé',
			select_custom_local: 'Local personnalisé',
			select_custom_ai: 'IA personnalisée',
			select_create_tournament: 'Créer un tournoi',
			select_join_tournament: 'Rejoindre un tournoi',
			select_search_error: '<p>Erreur lors de la recherche des joueurs</p>',
			select_invalid_data: '<p>Erreur : format des données invalide</p>',
			select_no_found: '<p>Aucun joueur trouvé</p>',
			select_invite_custom: 'Inviter à un jeu personnalisé',
			select_invite_normal: 'Inviter à une partie',
			select_invitation_sent: 'Invitation envoyée à',
			select_ready: 'Prêt à jouer',
			select_player_one: 'Joueur 1 : <span class="host">Par défaut</span>',
			select_player_two: 'Joueur 2 : <span></span>',
			select_start: 'Démarrer le jeu',
			select_view_tournament: 'Voir le tournoi en cours',
			select_add_account: 'Ajouter un compte',
			select_participants: 'Participants',
			select_tournament_player_one: 'Joueur 1 : <span class="player">Par défaut</span>',
			select_tournament_player_two: 'Joueur 2 : <span class="player">Par défaut</span>',
			select_tournament_player_three: 'Joueur 3 : <span class="player">Par défaut</span>',
			select_tournament_player_four: 'Joueur 4 : <span class="player">Par défaut</span>',
			select_start_tournament: 'Lancer le tournoi',
			select_tournament_name: 'Nom du tournoi',
			page_404: '404 Page non trouvée',
			reset_password: 'Entrez votre nouveau mot de passe',
			reset_password_again: 'Entrez à nouveau votre nouveau mot de passe',
			reset_message: "Rappel : le mot de passe doit contenir au moins une majuscule, une minuscule, un chiffre et un des caractères '*.-_'",
			reset_success: 'Mot de passe changé avec succès. Vous pouvez maintenant revenir à la page de connexion !',
			twofa_validate: 'Valider 2FA',
			invalid_code: 'Code invalide',

		}
	},
];

const navigatorLanguage = localStorage.getItem('language') ? localStorage.getItem('language') : window.navigator.language.substring(0, 2);
export let lang = locales.find(lang => lang.code === navigatorLanguage)
	? navigatorLanguage
	: 'en';

export function applyTranslation() {
	const currentLocale = locales.find(e => e.code === lang);
	const translations = currentLocale?.translations || {};

	const nodes = document.querySelectorAll('[translatekey]');
	const formNodes = document.querySelectorAll('[data-placeholder]');
	const buttonNodes = document.querySelectorAll('[data-value]');

	nodes?.forEach((node) => {
		const key = node.getAttribute('translatekey');
		if (key) {
			const translation = translations[key as keyof typeof translations] || key;
			node.innerHTML = translation;
		}
	});

	formNodes?.forEach((node) => {
		const key = node.getAttribute('data-placeholder');
		if (key) {
			const translation = translations[key as keyof typeof translations] || key;
			node.setAttribute('placeholder', translation);
		}
	});

	buttonNodes?.forEach((node) => {
		const key = node.getAttribute('data-value');
		if (key) {
			const translation = translations[key as keyof typeof translations] || key;
			node.setAttribute('value', translation);
		}
	});
}

export function getTranslation(key: string): string {
	const currentLocale = locales.find(e => e.code === lang);
	if (!currentLocale) return key;

	return currentLocale.translations[key as keyof typeof currentLocale.translations] || key;
}

export async function setLang(newLang: string) {
	if (lang === newLang) { return; }
	lang = newLang;
	try {
		const isLogged = await sendRequest('GET', '/islogged');
		if (isLogged && isLogged['logged'] === true) {
			const response = await sendRequest('PATCH', '/users', { language: lang });
			if (!response || response['error'])
				throw new Error('Error while saving new language');
		}
		localStorage.setItem('language', lang);
		await fetchDisplayTerms();
	}
	catch (error) {
		console.error(error);
	}
}
