services:
  frontend:
    build:
      context: srcs/frontend
    container_name: front
    ports:
      - "8000:80"
      - "8443:443"
    networks:
      - transcendence
  backend:
    build:
      context: srcs/backend
    container_name: back
    environment:
      HOSTNAME: "${HOSTNAME_FQDN}"
    env_file:
      - .env
    networks:
      - transcendence
networks:
  transcendence:
