import { crazyTokens } from "../games/connectFour/gameEngine";

const locales = [
	{
		code: 'en',
		flag: '🇬🇧',
		label: 'English',
		translations: {
			login_welcome: 'Welcome!',
			login_username: 'Username',
			login_password: 'Password',
			login_sign_in: 'Sign In',
			login_or: 'or',
			login_forgot_password: 'Forgot password?',
			login_no_account: `Don't have an account? `,
			login_sign_up: '&nbsp;Sign up',
			login_create_account: 'Create an account',
			login_repeat_password: 'Repeat the password',
			login_example_username: 'username-example123',
			login_example_email: 'example@email.com',
			login_create: 'Create account',
			login_return_to: 'or return to&nbsp;',
			login_accept_terms: 'By signing up, you agree to our Privacy and Terms Conditions.',
			terms_policy: 'Terms and Privacy Policy',
			language: 'English',
			login_recover_password: 'Recover your password',
			login_email: 'Introduce your email',
			login_submit: 'Submit',
			login_reset_password_message: `We'll send you an email to reset your password`,
			fill_all_fields: 'Fill in all the fields',
			username_too_short: 'Username too short',
			username_too_long: 'Username too long (max 16 characters)',
			username_allowed_chars: 'Username can only contain lowercase and digits',
			passwords_not_match: `Passwords don't match`,
			password_too_short: 'Password too short',
			password_musts: `Please use at least one uppercase, lowercase, number and '*.-_'`,
			incorrect_inputs: 'Username or Password may be incorrect',
			username_exists: 'Username already exists',
			email_exists: 'Email already in use',
			password_not_valid: 'Password is not valid',
			user_success: 'User create successfully',
			email_sent_successfully: 'Email sent succesfully! Go check it to reset your password',
			// Home Page
			home_header: 'Home Page',
			home_welcome: 'Welcome<span id="username" class="text-[var(--dark-pink)]"> Username</span>!',
			home_modify: 'Modify profile',
			home_profile: 'Profile settings',
			home_logout: 'Log out',
			home_games: 'Games',
			home_friends: 'Friends',
			home_messages: 'Messages',
			home_statistics: 'Statistics',
			home_moonbit: '✨ Welcome to Moonbit! ✨ ',
			home_first_p: 'Here, you can jump into classic games like <b class="text-white">Pong</b> or <b class="text-white">Connect Four</b>, play quick matches or join friendly <b class="text-white">tournaments</b>, whether it\'s with people nearby or online players from anywhere.',
			home_second_p: 'Feel like chatting? The <b class="text-white">chat</b> is always open: say hi, share a laugh, or plan your next game. You can also check out your <b class="text-white">Friends Page</b>, invite others to play, and see what they\'re up to.',
			home_third_p: 'And of course, this world is yours to make your own: visit your <b class="text-white">Profile</b> to personalize how you look and feel in this starry pixel space.',
			home_fourth_p: 'So go ahead: explore, play, and have fun. We’re happy you’re here. 🌟',
			stats_header: 'Statistics',
			stats_pong: 'Pong',
			stats_connect: 'Connect4',
			stats_historical: 'Historical',
			stats_dash: 'Dashboard',
			wins: 'Wins',
			losses: 'Losses',
			classic: 'Classic',
			chaos: 'Chaos',
			crazy_tokens: `CrazyTokens`,
			score_last_10: 'Score in the last 10 games',
			modify_header: 'Modify Profile',
			modify_upload_photo: 'Upload a photo',
			modify_create_avatar: 'Create an Avatar',
			modify_username: 'Username: ',
			modify_nick: 'Nick: ',
			modify_description: 'Description: ',
			modify_account: 'Account creation date: ',
			modify_wins: 'Total wins',
			modify_losses: 'Total losses',
			modify_avatar_creator: 'Avatar Creator',
			modify_save_changes: 'Save Changes',
			modify_empty_nickname: 'Nickname cannot be empty',
			modify_empty_description: 'Description cannot be empty',
			modify_select_options: 'Select 4 options',
			// Settings
			settings_title: 'Settings',
			settings_change_password: 'Change password',
			settings_two_factor: 'Configure 2 Factor-Authentication',
			settings_blocked_accounts: 'Blocked Accounts',
			settings_delete_account: 'Delete account',
			settings_current_password: 'Current Password',
			settings_new_password: 'New Password',
			settings_confirm_password: 'Confirm New Password',
			settings_submit_changes: 'Submit Changes',
			settings_auth: 'Two-Factor Auth',
			settings_auth_message: 'Introduce the 6-digits code associated to your account',
			settings_delete: 'Delete your account',
			settings_email: 'Introduce your email',
			settings_password: 'Introduce your password',
			settings_type_delete: `Type 'Delete'`,
			settings_fill_form: `Fill the form to delete your account`,
			settings_password_success: `Password changed successfully`,
			settings_wrong_delete: 'Incorrect confirm message',
			settings_delete_success: 'Account deleted successfully',
			settings_delete_message: `Your account has been deleted. <br/>If you log-in with your credentials in the next 30 days you'll recover it. <br/>We'll miss you!!`,
			settings_disable_2fa: `2FA disabled successfully`,
			settings_enable_2fa: `2FA enabled successfully`,
			settings_unblock_success: `User unblocked successfully`,
			settings_activate: 'Activate',
			settings_deactivate: 'Deactivate',
			// Friends
			friends_title: 'Friends',
			friends_list: 'Friends List',
			friends_invitations: 'Invitations',
			friends_search: 'Search a friend',
			friends_received: 'Received',
			friends_sent: 'Sent',
			friends_block_title: 'Block a friend',
			friends_cancel: 'Cancel',
			friends_block: 'Block',
			friends_block_m1: `Are you sure you want to <span class="text-[var(--alert)]">block</span> your friend?`,
			friends_block_m2: `Once done you can revert it in <span class="text-[var(--violet)]">settings</span>`,
			friends_online: 'Online',
			friends_offline: 'Offline',
			friends_delete: 'Delete',
			friends_pong_played: 'Pong Games Played: ',
			friends_pong_wins: 'Pong Wins Rate: ',
			friends_pong_losses: 'Pong Losses Rate: ',
			friends_connect_played: 'Connect Four Games Played: ',
			friends_connect_wins: 'Connect Four Wins Rate: ',
			friends_connect_losses: 'Connect Four Loses Rate: ',
			friends_user_not_found: 'User Not Found',
			// Messages
			messages_title: 'Chat Room',
			messages_friend_name: 'Friend name',
			messages_chat: 'Chat with your friends',
			messages_classic_pong: 'Classic Pong',
			messages_chaos_pong: 'Chaos Pong',
			messages_classic_connect: 'Classic Connect4',
			messages_crazy_connect: 'CrazyTokens Connect4',
			messages_not_friend: `You're not friends with this user`,
			// Select Game
			select_title: 'Select Game Mode',
			select_pong_description: 'Classic table tennis game. Challenge your friends in real-time!',
			select_pong_button: 'Play Pong',
			select_connect_title: 'Connect 4',
			select_connect_description: `Connect four pieces in a row to win. Strategic and fun!`,
			select_connect_button: 'Play Connect 4',
			select_tournament_title: 'Tournament',
			select_tournament_description: 'Create tournaments for both games!',
			select_tournament_button: 'Create Tournament',
			select_game_mode: 'Game Mode',
			select_normal_mode: 'Normal Mode',
			select_custom_mode: 'Custom Mode',
			select_remote: 'Remote Player',
			select_local: 'Local Game',
			select_play_ai: 'Play vs AI',
			select_custom_remote: 'Custom Remote',
			select_custom_local: 'Custom Local',
			select_custom_ai: 'Custom AI',
			select_create_tournament: 'Create Tournament',
			select_join_tournament: 'Join Tournament',
			select_search_error: '<p>Error searching players</p>',
			select_invalid_data: '<p>Error: Invalid data format</p>',
			select_no_found: '<p>No players found</p>',
			select_invite_custom: 'Invite to Custom Game',
			select_invite_normal: 'Invite to Game',
			select_invitation_sent: 'Invitation sent to',
		}
	},
	{
		code: 'es',
		flag: '🇪🇸',
		label: 'Español',
		translations: {
			login_welcome: 'Bienvenido',
			login_username: 'Nombre de usuario',
			login_password: 'Contraseña',
			login_sign_in: 'Iniciar Sesión',
			login_or: 'o',
			login_forgot_password: '¿Olvidaste tu contraseña?',
			login_no_account: `¿No tienes una cuenta? `,
			login_sign_up: '&nbsp;Regístrate',
			login_create_account: 'Registro',
			login_repeat_password: 'Repite la contraseña',
			login_example_username: 'usuario-ejemplo123',
			login_example_email: 'ejemplo@email.es',
			login_create: 'Create una cuenta',
			login_return_to: 'o vuelve a&nbsp;',
			login_accept_terms: 'Al registrarte, aceptas nuestros Términos y Condiciones de Privacidad',
			terms_policy: 'Términos y Políticas de Privacidad',
			language: 'Español',
			login_recover_password: 'Recupera tu contraseña',
			login_email: 'Introduce tu email',
			login_submit: 'Enviar',
			login_reset_password_message: `Te mandaremos un correo para que recuperes tu contraseña`,
			fill_all_fields: 'Rellena todos los campos',
			username_too_short: 'Nombre de usuario demasiado corto',
			username_too_long: 'Nombre de usuario demasiado largo (max 16 caracteres)',
			username_allowed_chars: 'El nombre de usuario sólo puede contener minúsculas y barra baja',
			passwords_not_match: `Las contraseñas no coinciden`,
			password_too_short: 'Contraseña demasiado corta',
			password_musts: `Por favor utiliza por lo menos una mayúscula, minúscula, número y '*.-_'`,
			incorrect_inputs: 'Nombre de usuario o contraseña incorrectos',
			username_exists: 'Nombre de usuario en uso',
			email_exists: 'Email en uso',
			password_not_valid: 'La contraseña no es válida',
			user_success: 'Usuario creado correctamente',
			email_sent_successfully: '¡Correo enviado con éxito! Revísalo para cambiar tu contraseña',
			// Home
			home_header: 'Página de Inicio',
			home_welcome: '¡Bienvenido<span id="username" class="text-[var(--dark-pink)]"> Username</span>!',
			home_modify: 'Modificar perfil',
			home_profile: 'Opciones del perfil',
			home_logout: 'Cerrar sesión',
			home_games: 'Juegos',
			home_friends: 'Amigos',
			home_messages: 'Mensajes',
			home_statistics: 'Estadísticas',
			home_moonbit: '✨ ¡Bienvenido a Moonbit! ✨ ',
			home_first_p: 'Aquí podrás disfrutar de juegos clásicos como <b class="text-white">Pong</b> o <b class="text-white">Cuatro en raya</b>, juega partidas rápidas o únete a <b class="text-white">torneos</b> amistosos.',
			home_second_p: '¿Quieres hablar un rato? El <b class="text-white">chat</b> siempre está abierto: di hola, comparte unas risas o prepara tu siguiente partida. También puedes echarle un vistazo a tu <b class="text-white">Página de Amigos</b>, invitar a otros a jugar y ver qué están haciendo.',
			home_third_p: 'Y por supuesto, este mundo te pertenece para hacerlo tuyo: visita tu <b class="text-white">Perfil</b> para personalizar cómo se te ve en este estrellado espacio pixelado.',
			home_fourth_p: 'Así que adelante: explora, juega, y diviértete. Estamos felices de que estés aquí. 🌟',
			stats_header: 'Estadísticas',
			stats_pong: 'Pong',
			stats_connect: 'Cuatro en raya',
			stats_historical: 'Historial',
			stats_dash: 'Panel',
			wins: 'Victorias',
			losses: 'Derrotas',
			classic: 'Clásico',
			chaos: 'Caos',
			crazy_tokens: 'Alocadas',
			score_last_10: 'Puntuación en las últimas 10 partidas',
			modify_header: 'Modificar Perfil',
			modify_upload_photo: 'Sube una foto',
			modify_create_avatar: 'Crea un avatar',
			modify_username: 'Nombre de usuario: ',
			modify_nick: 'Apodo: ',
			modify_description: 'Descripción: ',
			modify_account: 'Fecha de creación de cuenta: ',
			modify_wins: 'Victorias totales',
			modify_losses: 'Derrotas totales',
			modify_avatar_creator: 'Creador de Avatares',
			modify_save_changes: 'Guardar Cambios',
			modify_empty_nickname: 'El apodo no puede estar vacío',
			modify_empty_description: 'La descripción no puede estar vacía',
			modify_select_options: 'Selecciona 4 opciones',
			// Settings
			settings_title: 'Ajustes',
			settings_change_password: 'Cambiar contraseña',
			settings_two_factor: 'Configurar Autenticación de 2 Factores',
			settings_blocked_accounts: 'Cuentas bloqueadas',
			settings_delete_account: 'Eliminar cuenta',
			settings_current_password: 'Contraseña Actual',
			settings_new_password: 'Nueva Contraseña',
			settings_confirm_password: 'Confirma la Nueva Contraseña',
			settings_submit_changes: 'Enviar Cambios',
			settings_auth: '2FA',
			settings_auth_message: 'Introduce el código de 6 dígitos asociado a tu cuenta',
			settings_delete: 'Elimina tu cuenta',
			settings_email: 'Introduce tu correo',
			settings_password: 'Introduce tu contraseña',
			settings_type_delete: `Introduce 'Delete'`,
			settings_fill_form: `Rellena el formulario para eliminar tu cuenta`,
			settings_password_success: `Contraseña cambiada con éxito`,
			settings_wrong_delete: 'Mensaje de confirmación incorrecto',
			settings_delete_success: 'Cuenta eliminada con éxito',
			settings_delete_message: `Tu cuenta ha sido eliminada. <br/>Si inicias sesión en los próximos 30 días la recuperarás. <br/>¡Te echaremos de menos!`,
			settings_disable_2fa: `2FA desactivado con éxito`,
			settings_enable_2fa: `2FA habilitado con éxito`,
			settings_unblock_success: `Usuario desbloqueado con éxito`,
			settings_activate: 'Activar',
			settings_deactivate: 'Desactivar',
			// Friends
			friends_title: 'Amigos',
			friends_list: 'Lista de Amigos',
			friends_invitations: 'Invitaciones',
			friends_search: 'Buscar a un amigo',
			friends_received: 'Recibidas',
			friends_sent: 'Enviadas',
			friends_block_title: 'Bloquea a un amigo',
			friends_cancel: 'Cancelar',
			friends_block: 'Bloquear',
			friends_block_m1: `¿Estás seguro de que quieres <span class="text-[var(--alert)]">bloquear</span> a esta persona?`,
			friends_block_m2: `Una vez hecho, puedes revertirlo en <span class="text-[var(--violet)]">ajustes</span>`,
			friends_online: 'En línea',
			friends_offline: 'Desconectado',
			friends_delete: 'Eliminar',
			friends_pong_played: 'Partidas de Pong Jugadas: ',
			friends_pong_wins: 'Victorias de Pong: ',
			friends_pong_losses: 'Derrotas de Pong: ',
			friends_connect_played: 'Partidas de Cuatro en Raya Jugadas: ',
			friends_connect_wins: 'Victorias de Cuatro en Raya: ',
			friends_connect_losses: 'Derrotas de Cuatro en Raya: ',
			friends_user_not_found: 'Usuario no encontrado',
			// Messages
			messages_title: 'Sala de Chat',
			messages_friend_name: 'Nombre de amigo',
			messages_chat: 'Habla con tus amigos',
			messages_classic_pong: 'Pong Clásico',
			messages_chaos_pong: 'Pong Caos',
			messages_classic_connect: 'Cuatro en Raya Clásico',
			messages_crazy_connect: 'Cuatro en Raya Fichas Alocadas',
			messages_not_friend: `No eres amigo de este usuario`,
			// Select Game
			select_title: 'Selección de Modo de Juego',
			select_pong_description: 'El clásico juego de tenis de mesa. ¡Desafía a tus amigos en tiempo real!',
			select_pong_button: 'Jugar al Pong',
			select_connect_title: 'Cuatro en Raya',
			select_connect_description: `Conecta cuatro piezas seguidas para ganar. ¡Estratégico y divertido!`,
			select_connect_button: 'Jugar Cuatro en Raya',
			select_tournament_title: 'Torneo',
			select_tournament_description: '¡Crea torneos para ambos juegos!',
			select_tournament_button: 'Crear Torneo',
			select_game_mode: 'Modo de Juego',
			select_normal_mode: 'Modo Normal',
			select_custom_mode: 'Modo Personalizado',
			select_remote: 'Juego en Remoto',
			select_local: 'Juego en Local',
			select_play_ai: 'Juego contra la IA',
			select_custom_remote: 'Remoto Personalizado',
			select_custom_local: 'Local Personalizado',
			select_custom_ai: 'IA Personalizada',
			select_create_tournament: 'Crear un Torneo',
			select_join_tournament: 'Unirse a un Torneo',
			select_search_error: '<p>Error buscando jugadores</p>',
			select_invalid_data: '<p>Error: Formato de dato inválido</p>',
			select_no_found: '<p>Ningún jugador encontrado</p>',
			select_invite_custom: 'Invitar a juego personalizado',
			select_invite_normal: 'Invitar a jugar',
			select_invitation_sent: 'Invitación enviada a',
		}
	},
	{
		code: 'fr',
		flag: '🇫🇷',
		label: 'Français',
		translations: {
			login_welcome: 'Bienvenue !',
			login_username: `Nom d'utilisateur`,
			login_password: 'Mot de passe',
			login_sign_in: 'Se connecter',
			login_or: 'ou',
			login_forgot_password: 'Mot de passe oublié ?',
			login_no_account: `Vous n'avez pas de compte ? `,
			login_sign_up: `&nbsp;Inscrivez-vous`,
			login_create_account: 'Enregistrement',
			login_repeat_password: 'Répète le mot de passe',
			login_example_username: 'utilisateur-exemple123',
			login_example_email: 'exemple@email.fr',
			login_create: 'Creez-vous un compte',
			login_return_to: 'ou returnez au&nbsp;',
			login_accept_terms: `En vous inscrivant, vous acceptez nos conditions d'utilisation relatives à la protection de la vie privée.`,
			terms_policy: 'Conditions et Politique de confidentialité',
			language: 'Français',
			fill_all_fields: 'Remplir tous les champs',
			username_too_short: `Nom d'utilisateur trop court`,
			username_too_long: `Nom d'utilisateur trop long (max 16 caractères)`,
			username_allowed_chars: `Le nom d'utilisateur ne peut contenir que des minuscules et des traits de soulignement`,
			passwords_not_match : `Les mots de passe ne correspondent pas`,
			password_too_short : 'Mot de passe trop court',
			password_musts : `Veuillez utiliser au moins une majuscule, une minuscule, un chiffre et '*.-_'`,
      home_header: '',
      home_welcome: '',
      home_modify: '',
      home_profile: '',
      home_logout: '',
      home_games: '',
      home_friends: '',
      home_messages: '',
      home_statistics: '',
      home_moonbit: '',
      home_first_p: '',
      home_second_p: '',
      home_third_p: '',
      home_fourth_p: '',
      stats_header: '',
      stats_pong: '',
      stats_connect: '',
      stats_historical: '',
      stats_dash: '',
      wins: '',
      losses: '',
      score_last_10: '',
      modify_header: '',
      modify_create_avatar: '',
      modify_username: '',
      modify_nick: '',
      modify_description: '',
      modify_account: '',
      modify_wins: '',
      modify_losses: '',
      modify_avatar_creator: '',
      modify_save_changes: '',
		}
	},
];

const navigatorLanguage = 'es';

let lang = locales.find(lang => lang.code === navigatorLanguage)
						? navigatorLanguage
						: 'en';

export function applyTranslation() {
	const translations = locales.find(e => e.code === lang)?.translations;

	// localStorage.setItem("") = lang;

	const nodes = document.querySelectorAll('[translatekey]');
	const formNodes = document.querySelectorAll('[data-placeholder]');
	const buttonNodes = document.querySelectorAll('[data-value]');

	if (!nodes) return;

	nodes?.forEach((node) => {
		const key = node.getAttribute('translatekey');
		const translation = translations[key] || key;
		node.innerHTML = translation;
	});
	formNodes?.forEach((node) => {
		const key = node.getAttribute('data-placeholder');
		const translation = translations[key] || key;
		node.setAttribute('placeholder', translation);
	});
	buttonNodes?.forEach((node) => {
		const key = node.getAttribute('data-value');
		const translation = translations[key] || key;
		node.setAttribute('value', translation);
	})
}

function generateLanguageSelector() {
	const container = document.querySelector('#languageSelector');

	if (!container) return;

	locales.forEach((locale) => {locales.find(e => e.code === lang)?.translations
		const element = document.createElement('button');
		element.className = 'dropdown-item';
		element.type = 'button';
		element.innerHTML = `${locale.flag} ${locale.label}`;
		element.onclick = () => {
			lang = locale.code;
			applyTranslation();
		}
		container.appendChild(element);
	});
}

export function getTranslation(key: string) {
	const translation = locales.find(e => e.code === lang).translations[key];
	return (translation || key);
}
